name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: mkdir -p semantic_release_modules
      - run: npm install semantic-release @semantic-release/changelog @semantic-release/git --prefix ./semantic_release_modules
      - run: ./semantic_release_modules/node_modules/.bin/semantic-release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}